### ISSUE TITLE
No download source code option

### ISSUE THREAD

**Issue by Meiting-Wang** [haghish/github#12]
When I use `github install username/repository, stable` or `github install username/repository, version()`, It will additionally download the source code to the current directory except the .ado files to the plus directory. I want to find a option to prevent it, but I have no way to go, so I have to delete the source code in current directory by  hand.

It would be great if this Stata command(`github install`) have a option to achieve this function automatically. 

Ps, My Stata version is MP 15.1.

Thanks
Meiting Wang

**Comment by Meiting-Wang** [comment]
My Stata version is MP 15.1.

**Comment by haghish** [comment]
The reason is that the stable releases and previous versions are stored in a zip file and stata cannot access the files individually, unless it is downloaded and unzipped. 

It is possible to add a function to automatically remove the downloaded directory, which would only require to scan the files in the zip file and try to remove them one by one, followed by removing the directory. If you like to add this function, go to this section: 

https://github.com/haghish/github/blob/ac338e1bf391eebd70106bfc5aa17348cc296eaf/github.ado#L492

**Comment by Meiting-Wang** [comment]
Using some time, I find `! rmdir folder /s /q` can delete a folder with some files or subfolders quickly, but the screen will flash when calling cmd(My system is windows10). The same goes for putting this command line(`! rmdir folder /s /q`) in the ado file.
